server:
  port: 7070

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8085/realms/jungleinenglish-realm
  datasource:
    url: jdbc:mysql://localhost:3306/chatdb5?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true



  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: llama2


