server:
  port: 8081

spring:
  application:
    name: courses-service
  datasource:
    url: jdbc:mysql://localhost:3306/courses_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect


logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# If you still need a URL for lessons-service, DON'T use localhost.
# Either remove it and use discovery-based calls, or set:
lessons:
  service:
    url: http://lessons-service