server:
  port: 8082
  tomcat:
    max-swallow-size: 200MB
    max-http-form-post-size: 200MB


spring:
  application:
    name: lessons-service
  datasource:
    url: jdbc:mysql://localhost:3306/lessons_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB


app:
  upload:
    base-dir: uploads

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

courses:
  service:
    url: http://courses-service