spring.application.name=api-gateway
server.port=8081

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Activer discovery automatique
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true 


# Gateway MVC reads routes from the mvc namespace
spring.cloud.gateway.mvc.routes[0].id=reclamation-service
spring.cloud.gateway.mvc.routes[0].uri=lb://reclamationreponsemicroservice
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/complaints,/complaints/**