spring.application.name=todomodule

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/todomodule?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
server.port=8081
# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

# Swagger UI / OpenAPI (springdoc 3.x)
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=brrn99amine@gmail.com
spring.mail.password=rgpqqabzpzjihexy
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
# Logging
logging.level.org.springframework.security=DEBUG
logging.level.tn.esprit.todomodule.security=DEBUG
logging.level.tn.esprit.todomodule.security.jwt=DEBUG

# Keycloak Integration
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8085/realms/jungleinenglish-realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8085/realms/jungleinenglish-realm/protocol/openid-connect/certs
